# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-analytics

exclude: [vendor]

# Setup
title:               Thoughts on Code
tagline:             '@_skryl_'
description:         'Musings on code and technology'
url:                 http://blog.skryl.org
baseurl:             ''
paginate:            5
host:                localhost
port:                4000

# About/contact
author:
  name:              Alex Skryl
  url:               https://twitter.com/skryl
  email:             aleksey.skryl@gmail.com
  github:            https://github.com/skryl
  homepage:          https://skryl.org

jekyll_analytics:
  GoogleAnalytics:
    id: UA-29940604-1