# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-analytics
  - jekyll-redirect-from
  - jekyll-tagging-related_posts

exclude: [vendor]

# Setup
title:               Thoughts
tagline:             '@skryl.org'
description:         'Musings on code and technology'
url:                 http://blog.skryl.org
baseurl:             ''
paginate:            5
host:                localhost
port:                4000

# About/contact
author:
  name:              Alex Skryl
  url:               https://twitter.com/skryl
  email:             aleksey.skryl@gmail.com
  github:            https://github.com/skryl
  homepage:          https://skryl.org
  contact:
    linkedin:  https://www.linkedin.com/in/skryl
    github:    https://github.com/skryl
    twitter:   https://twitter.com/_skryl_


jekyll_analytics:
  GoogleAnalytics:
    id: UA-29940604-1